# Generated by Django 3.2.6 on 2021-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('thumbnail', models.ImageField(upload_to='blog/photo/')),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
